name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: install_packages
      run: "sudo apt-get update; sudo apt-get -y install cppcheck-gui cppcheck clang valgrind"
    - name: cppcheck
      run: "cd examples/foo; make all"
<<<<<<< HEAD
=======

>>>>>>> bd2bbb75a2e412d5b7cdd4c7e5d590ad6d3b00a4
